security_group:
   name: "ansible-master"
   description: "Ansible master server"
   rules:
      - cidr_ip: "0.0.0.0/0"
        from_port: "22"
        proto: "tcp"
        to_port: "22"
   rules_egress:
      - type: "egress"
        cidr_ip: "0.0.0.0/0"
        from_port: "22"
        proto: "tcp"
        to_port: "22" # ssh
      - type: "egress"
        cidr_ip: "0.0.0.0/0"
        from_port: "80"
        proto: "tcp"
        to_port: "80" # yum
      - type: "egress"
        cidr_ip: "0.0.0.0/0"
        from_port: "443"
        proto: "tcp"
        to_port: "443" # pip
        

instance:
   security_group: "{{security_group.name}}"
   wait_timeout: "500"
   size: "t1.micro"
# "us-east-1"
   region: "us-west-2"
   ami: "ami-ff527ecf" #"ami-8e682ce6"
   count: 1
   public_ip: "yes"
   tags:
       Name: "ansible-master"
   subnets: 
     - "PrivateSubnet1"
#     - "PrivateSubnet2"
   volumes:
     - device_name: /dev/sda1
       volume_size: 8
       delete_on_termination: true