security_group:
   http:
      name: "http"
      description: "web server"
      rules:
         ingress:
         - cidr_ip: "0.0.0.0/0"
           from_port: "22"
           proto: "tcp"
           to_port: "22"
         - cidr_ip: "0.0.0.0/0"
           from_port: "80"
           proto: "tcp"
           to_port: "80"
