
#- name: yum upgrade all packages
#  yum: name=* state=latest
#  sudo: yes
#  with_items: "{{ec2_details.results}}"

#- name: debug elasticsearch_ip
#  debug: msg="{{elasticsearch_ip}}" 
#  ignore_errors: yes
#  when: elasticsearch_ip is defined
  
#    ec2_details: "{{hostvars.localhost.ec2_details}}"
#    elasticsearch_ip_address: "{{ec2_details.results[0].instance_ids[0]}}"
#    elasticsearch_ip_address_orig: "{{hostvars.localhost.elb_info.elb.dns_name}}"
    
- name: debug msg

  debug: msg"-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
- name: groups
  debug: msg="{{groups}}"
  
- name: elasticsearch_ip_address
  debug: msg="{{elasticsearch_ip_address}}"
  when: elasticsearch_ip_address is defined

- name: groups.elasticsearch_servers[0]
  debug: msg="{{groups.elasticsearch_servers[0]}}"
  when: groups.elasticsearch_servers is defined
  
- name: elasticsearch_ip_address
  debug: msg="{{elasticsearch_ip_address}}"
  when: groups.elasticsearch_ip_address is defined
  
- name: debug msg
  debug: msg"-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"
- name: debug elasticsearch_ip_address
  debug: msg="{{elasticsearch_ip_address}}"

- name: debug hostvars.localhost
  debug: msg="{{hostvars.localhost}}"

#  "{{hostvars.localhost.elb_info.elb.dns_name}}"
- name: Download Logstash rpm
  get_url: url={{package_url}} dest=/tmp/{{file_name}} force=yes validate_certs=no
  with_items: "{{ec2_details.results}}"
  
- name: Make log dir
  file: path="{{log_dir}}" state="directory"
  with_items: "{{ec2_details.results}}"
  
- name: add uname to /etc/hosts
  shell: "echo \"127.0.0.1 `uname -n`\" >> /etc/hosts"
  
- name: Install Logstash
  yum: name="/tmp/{{file_name}}"
  with_items: "{{ec2_details.results}}"
  
- name: Delete Logstash rpm
  file: path="/tmp/{{file_name}}" state="absent"
  with_items: "{{ec2_details.results}}"
  
- name: Load config file logstash.conf with proper values
  template: src="logstash.conf.yml" dest="/etc/logstash/conf.d/logstash.conf"
  with_items: "{{ec2_details.results}}"
    


- name: Restart Logstash
  action: service name=logstash state=restarted
  with_items: "{{ec2_details.results}}"
