---
    
  # Install required library for Ansible
  - name: Install libselinux-python
    sudo: yes
    yum: name=libselinux-python state=latest
    
  - name: Install nginx
    sudo: yes
    yum: name=nginx state=latest
    
  - name: Configure site 
    template: src="site.conf.j2"
      dest="/etc/nginx/conf.d/{{inventory_hostname}}.conf"
      mode=644
    sudo: yes
    
  ###
  # Open port.
  ###
  - name: Open the correct IPTables ports
    lineinfile: dest=/etc/sysconfig/iptables
                regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
                line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
                insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
    with_items:
      - { protocol: tcp, port: "{{ port_num }}" }
    sudo: yes
  
  - name: restart iptables
    service: name=iptables state=restarted enabled=yes
    sudo: yes
  ###
  # END Open port.
  ###
  
  - name: mkdir www server dir
    file: path=/var/www/{{inventory_hostname}} recurse=yes owner=nginx group=nginx state=directory
    sudo: yes

  - name: Transfer index.htm
    copy: src=../files/index.htm dest=/var/www/{{inventory_hostname}}/index.htm
    sudo: yes

  - name: Restart nginx
    service: name=nginx state=restarted enabled=yes
    sudo: yes
    
  - debug: msg="curl http://{{ inventory_hostname }}:{{ port_num }}"