---
# ansible-playbook deploy_elasticsearch.yml -vv --private-key=/path/to/ec2/pri/key

- name: Stage instance(s)
  hosts: local
  connection: local
  user: root
  gather_facts: false
  
  tags:
      - stage

  vars:
      keypair: {{ key_name }}
      instance_type: t1.micro
      security_group: {{ security_group_name }}
      image: {{ ami_image }}
      instance_count: 2

  # Launch 2 instances with the following parameters.  Register the output.

  tasks:
  
    - name: elasticsearch ec2 group
      ec2_group:
      name: elasticsearch
      description: an example EC2 group
      vpc_id: 666
      region: eu-west-1a
      aws_secret_key: "{{ lookup ('env', 'AWS_SECRET_ACCESS_KEY') }}"
      aws_access_key: "{{ lookup ('env', 'AWS_ACCESS_KEY_ID') }}"
      rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 9200
        to_port: 9200
        cidr_ip: 10.0.0.0/8
      - proto: tcp
        from_port: 9300
        to_port: 9300
        cidr_ip: 10.0.0.0/8
      - proto: udp
        from_port: 10050
        to_port: 10050
        cidr_ip: 10.0.0.0/8
      - proto: udp
        from_port: 10051
        to_port: 10051
        group_id: sg-12345678
      - proto: all
        # the containing group name may be specified here
        group_name: example
    - name: Launch instance 
        local_action: ec2 keypair=${keypair} group=${security_group} instance_type=${instance_type} image=${image} wait=yes count=${instance_count}
        register: ec2
    
    # Use with_items to add each instances public IP to a new hostgroup for use in the next play.

    - name: Add new instances to host group
      local_action: add_host name=${item.public_dns_name} groups=deploy
      with_items: ${ec2.instances}

    # Use the ec2_vol module to create volumes for attachment to each instance. Use with_items to attach to each instance (by returned id) launched previously.

    #- name: Create a volume and attach
    #  local_action: ec2_vol volume_size=20 instance=${item.id}
    #  with_items: ${ec2.instances}

    - name: Wait for SSH to be available 
      local_action: wait_for host=${item.public_dns_name} port=22
      with_items: ${ec2.instances}
 
    - name: Breathing room (Ansible uses python apt, has issues running directly after boot)
      pause: seconds=15

# This play targets the new host group

- name: Configure instance
  hosts: deploy
  user: ubuntu
  sudo: yes
  gather_facts: true

  tags:
    - config
    - configure 

  # Install Java, install Elasticsearch, replace settings....

  tasks:

    - name: Install JRE
      apt: pkg=openjdk-6-jre-headless state=latest install_recommends=no update_cache=yes

    - name: Download ElasticSearch package
      get_url: url=http://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.0.deb dest=~/elasticsearch-0.90.0.deb

    - name: Install ES .deb file
      shell: dpkg -i ~/elasticsearch-0.90.0.deb
      notify: restart elasticsearch

    - name: Install cloud-aws plugin
      shell: /usr/share/elasticsearch/bin/plugin -install elasticsearch/elasticsearch-cloud-aws/1.11.0
      notify: restart elasticsearch

    - name: Make elasticsearch config dir
      file: path=/etc/elasticsearch/ state=directory

    - name: Copy over Elasticsearch settings      
      copy: src=./elasticsearch/elasticsearch.yml dest=/etc/elasticsearch/elasticsearch.yml
      notify: restart elasticsearch
 
  handlers:
    - name: restart elasticsearch
      action: service name=elasticsearch state=restarted

