########################################################
# Create Infrastructure
########################################################
- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    deploy_group_name: ansible-master
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/ansible-master.yml
  roles:
    # Gather master network details via ec2_cloudformation call
    - {role: ec2_cloudformation}
    - {role: ec2_security_group}
    - {role: ec2_instances}



- name: Delete devel EC2 instances
  hosts: security_group_ansible-master           # <-- MAGIC IS HERE!
  connection: local
  gather_facts: False
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/ansible-master.yml
  tasks:
  - name: Terminate {{ec2_id}} instance in {{aws_region}}
    local_action:
        module: ec2
        state: 'absent'
        region: '{{instance.region}}'
        instance_ids: '{{ec2_id}}'

  # Pause for 5 minutes to build app cache.
  - pause: seconds=30

- name: Delete 'ansible-master' security group
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/ansible-master.yml
  tasks:
  - name: Take 'ansible-master' security group down
    local_action:
        module: ec2_group
        name: ansible-master
        description: "A Security group"
        region: "{{instance.region}}"
        state: 'absent'




########################################################
# Setup ansible master on aws
########################################################
- name: Setup ansible
  hosts: ansible-master
  hosts: localhost
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/ansible-master.yml
  roles:  
    - {role: ansible-master}



