- name: Create instances
  hosts: localhost
  connection: local
  gather_facts: False
  
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/elasticsearch.yml
  roles:
    - {role: ec2_cloudformation}
    - {role: ec2_instance}
    
    
- name: Deploy elasticsearch
  hosts: deploy_to
  user: ec2-user
  sudo: yes
  gather_facts: true
  
  vars_files:
    - ./group_vars/all.yml
    - ./group_vars/elasticsearch.yml
  roles:
    - {role: elasticsearch}
    