- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - region: "us-east-1"
    - stack_name: "BravoInfrastructure-integration"
  roles:
    - { role: ec2_cloudformation, tags: ['report'] }
    
