- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    - stack_name: "base-ubuntu"
    - region: "us-west-2"
    - key_name: "key_pair_oregon"
    - instance_size: "t1.micro"
    - template_name: "Single_Ubuntu.json"
  tasks:
    - include: ../roles/cloudformation/tasks/main.yml
    
