
#- name: yum upgrade all packages
#  yum: name=* state=latest
#  sudo: yes
#  with_items: "{{ec2_details.results}}"
 
###########
# XXXXXX THIS MUST BE HERE....... PUT BACK ONCE DONE DEBUGGING
#- set_fact:   
#    elasticsearch_ip_address: "{{hostvars.localhost.elb_info.elb.dns_name}}"

- name: Make log dir
  file: path="{{log_dir}}" state="directory"
  with_items: "{{ec2_details.results}}"
  
- name: Make install dir
  file: path="{{install_dir}}" state="directory"
  with_items: "{{ec2_details.results}}"
  
- name: add uname to /etc/hosts
  shell: "echo \"127.0.0.1 `uname -n`\" >> /etc/hosts"
  
#- name: Copy kibana tgz to tmp dir
#  copy: src="/tmp/{{file_name}}" dest="/tmp/{{file_name}}"
  
- name: Install Kibana
  unarchive: src="/tmp/{{file_name}}" dest="{{install_dir}}"
  
- name: Delete Kibana tar
  file: path="/tmp/{{file_name}}" state="absent"
  with_items: "{{ec2_details.results}}"
  
- name: Load config file kibana.conf with proper values
  template: src="kibana.yml" dest="{{install_dir}}/{{install_subdir}}/config/kibana.yml"
  with_items: "{{ec2_details.results}}"
    

- name: Setup kibana4 service
  template: src="kibana4.init.yml" dest="/etc/init.d/kibana4" mode=0755
  with_items: "{{ec2_details.results}}"
    
- name: Restart Kibana
  action: service name=kibana4 state=restarted
  with_items: "{{ec2_details.results}}"
