- name: Destroy EC2 Security Group
  ec2_group:
    name: "{{security_group.name}}"
    description: "{{security_group.description}}"
    vpc_id: "{{ec2_cloudformation_results['VPCId']}}"
    region: "{{ master.region }}"
    state: absent
  tags: 
    - destroy