

- name: Implement cloudformation file.
  debug: msg="Import cloudformation file to aws"
  
- name: gather cloudformation data
  cloudformation_info:
    region: "{{ master.region }}"
    stack_name: "{{ master.stack_name }}"
  register: ec2_cloudformation_results 
  ignore_errors: yes
  tags: 
    - create
    - report
    
- name: debug
  debug: msg="{{ec2_cloudformation_results}}"
  ignore_errors: yes
  tags: 
    - create
    - report
    