#!/bin/bash
#
#       /etc/init.d/kibana

# Set defaults.
PROG="kibana"
PID_DIR="/var/run"
PID_FILE="$PID_DIR/${PROG}.pid"
LOCK_FILE="/var/lock/subsys/$prog"
KIBANA_USER="kibana"
KIBANA_EXEC="/usr/share/kibana4/kibana-4.0.1-linux-x64/bin/kibana"

LOG_DIR="/var/log/kibana4"
LOG_FILE="$LOG_DIR/kibana.log"


# Execute init.d functions
. /etc/rc.d/init.d/functions

case "$1" in
    start)
       mkdir -p "$PID_DIR"
       mkdir -p "$LOG_DIR"
   
       # This is an artifact of the way I set things up and is a hacky solution to
       # fix a race condition, so copy with caution
       sleep 10
   
       echo "Starting Kibana..."
       $KIBANA_EXEC 1>$LOG_FILE 2>&1 &
#       su $KIBANA_USER -c "$KIBANA_EXEC 1>$LOG_FILE 2>&1 &"
       echo $! > "$PID_FILE"
       echo "Kibana started with pid $!"
       
       ;;
    stop)
        echo -n "Stopping Kibana: "
#        su $KIBANA_USER -c "kill `cat $pid_file`"
        kill `cat $pid_file`
        retval=$?
        [ $retval -eq 0 ] && rm -f $LOCK_FILE
        echo "OK"
        ;;
    status)
        status -p $PID_FILE kibana
        exit $?
        ;;
    *)
        echo "Usage: `basename $0` start|stop|status"
        exit 1
esac

exit 0