
#- include: translate_json.yml
#  tags: [test]
  
- include: stack_destroy.yml
  tags: [destroy]
    
- include: stack_create.yml
  tags: [create]

- include: stack_report.yml
  tags: [report]

- include: stack_destroy.yml
  tags: [delete]
    
