# http://docs.ansible.com/cloudformation_module.html
- name: Create AWS Cloudformation
  cloudformation:
    stack_name: "{{stack_name}}"
    state: "present"
    region: "{{region}}"
    disable_rollback: true
    template: "roles/cloudformation/templates/{{template_name}}"
    template_parameters:
      KeyName: "{{key_name}}"
      InstanceType: "{{instance_size}}"
  register: cloud_info