########################################
# Register the ec2 instances to the ELB
########################################
- name: debug ec2_details
  debug: msg="{{ec2_details}}"
  ignore_errors: yes
  when: ec2_details is defined
  
- name: debug elb_info
  debug: msg="{{elb_info}}"
  ignore_errors: yes
  when: elb_info is defined
  
  
  
  
- name: 
  ec2_elb:
    instance_id: "{{item.instances[0].id}}"
    ec2_elbs: "{{elb_info.elb.name}}"
    state: present
    wait: 'yes'
    region: "{{instance.region}}"
    enable_availability_zone: no
    wait_timeout: 301
  with_items: "{{ec2_details.results}}"
    
     