####################
# Create the elb
####################
- name: create elb
  ec2_elb_lb:
    name: "{{ elb.name }}"
    state: present
    region: "{{instance.region}}"
    zones: "{{ elb.zones }}"
    listeners: "{{ elb.listeners }}"
    health_check: "{{ elb.health_check }}"
  register: elb_info
  
- name: log elb_info
  debug: msg= {{elb_info}}
  
  
  
- name: log elb_info
  debug: msg= {{elb_info.elb.public_dns_name}}
