
#- name: yum upgrade all packages
#  yum: name=* state=latest
#  sudo: yes
#  with_items: "{{ec2_details.instances}}"
  
- name: download ElasticSearch rpm
  get_url: url={{package_url}} dest=/tmp/{{file_name}} force=yes validate_certs=no
  with_items: "{{ec2_details.instances}}"
  
- name: Make log dir
  file: path="{{log_dir}}" state="directory"
  with_items: "{{ec2_details.instances}}"
  
- name: add uname to /etc/hosts
  shell: "echo \"127.0.0.1 `uname -n`\" >> /etc/hosts"
  
  
- name: Install ElasticSearch
  yum: name="/tmp/{{file_name}}"
  with_items: "{{ec2_details.instances}}"
  
- name: Delete ElasticSearch rpm
  file: path="/tmp/{{file_name}}" state="absent"
  with_items: "{{ec2_details.instances}}"
  
- name: Install head plugin
  shell: "{{install_dir}}/bin/plugin -install mobz/elasticsearch-head"
  with_items: "{{ec2_details.instances}}"
- name: Install bigdesk plugin
  shell: "{{install_dir}}/bin/plugin -install lukas-vlcek/bigdesk"
  with_items: "{{ec2_details.instances}}"
- name: Install cloud-aws plugin
  shell: "{{install_dir}}/bin/plugin install elasticsearch/elasticsearch-cloud-aws/2.4.1"
  with_items: "{{ec2_details.instances}}"

- name: Load config file elasticsearch.yml with proper values
  template: src="elasticsearch.yml" dest="/etc/elasticsearch/elasticsearch.yml"
  with_items: "{{ec2_details.instances}}"
    
- name: restart elasticsearch
  action: service name=elasticsearch state=restarted
  with_items: "{{ec2_details.instances}}"

# below, host should be  # "{{item.private_ip}}"
- name: Wait for elasticsearch to be available 
  local_action: 
    module: wait_for 
      host="{{item.public_ip}}"
      port=9300
      delay=5
      timeout=300
  with_items: "{{ec2_details.instances}}"
  sudo: false
    