input { 
  file { path => "/tmp/logstash.txt" } 
} 
input {
  tcp {
    port => 4560
    codec => json
  }
}
output { 
  elasticsearch { 
    host => "{{elasticsearch_ip_address}}" protocol => "http" 
  } 
}